#!/usr/bin/env python3
"""
FIR Filter Coefficient Generator for FM/DMB Repeater

Generates 16-bit fixed-point coefficients for:
  - FIR1: DMB channel select (47 taps, decimate-by-2)
  - FIR2: DMB matched filter (104 taps)
  - Test tone generation and frequency response plotting

Usage:
  python fir_coeff_gen.py                    # Generate all coefficients
  python fir_coeff_gen.py --plot             # Show frequency response
  python fir_coeff_gen.py --fs 80e6 --fc 1.536e6 --taps 47 --output fir1_coeff.coe
"""

import numpy as np
import argparse
import os
import sys

# ==============================================================================
# Constants
# ==============================================================================
COEFF_DIR = os.path.join(os.path.dirname(__file__), '..', 'fpga', 'rtl')
FS_DMB = 80e6           # 80 MHz sampling (after DDC)
BW_DMB = 1.536e6        # DMB channel bandwidth (1.536 MHz)
FS_DMB_BB = 2.048e6     # Baseband rate after CIC decimation

# ==============================================================================
# FIR Design Functions
# ==============================================================================

def design_fir(num_taps, fs, passband_freq, stopband_freq=None, window='hamming'):
    """
    Design a low-pass FIR filter using window method.

    Args:
        num_taps: Number of filter taps
        fs: Sampling frequency (Hz)
        passband_freq: Passband edge frequency (Hz)
        stopband_freq: Stopband start frequency (Hz) — if None, auto-calculate
        window: Window type ('hamming', 'hanning', 'blackman', 'kaiser')

    Returns:
        coeffs: Normalized floating-point coefficients
    """
    if num_taps % 2 == 0:
        num_taps += 1  # Force odd for symmetric

    nyquist = fs / 2.0
    wc = passband_freq / nyquist  # Normalized cutoff

    if stopband_freq is None:
        # Auto: transition band = 20% of passband
        stopband_freq = passband_freq * 1.2
    wt = stopband_freq / nyquist

    # Ideal LPF impulse response (sinc)
    n = np.arange(num_taps)
    center = (num_taps - 1) / 2.0
    h_ideal = 2 * wc * np.sinc(2 * wc * (n - center))

    # Apply window
    if window == 'hamming':
        window_fn = np.hamming(num_taps)
    elif window == 'hanning':
        window_fn = np.hanning(num_taps)
    elif window == 'blackman':
        window_fn = np.blackman(num_taps)
    elif window == 'kaiser':
        window_fn = np.kaiser(num_taps, beta=8.0)
    elif window == 'bartlett':
        window_fn = np.bartlett(num_taps)
    else:
        window_fn = np.ones(num_taps)

    coeffs = h_ideal * window_fn

    # Normalize to unity DC gain
    coeffs = coeffs / np.sum(coeffs)

    return coeffs


def quantize_coeffs(coeffs, bits=16):
    """
    Quantize floating-point coefficients to N-bit signed fixed-point.

    Args:
        coeffs: Floating-point coefficients (-1.0 to 1.0)
        bits: Bit width (default: 16)

    Returns:
        quantized: Integer array in Q(1, bits-2) format
        hex_str: Hex string array for Verilog $readmemh
    """
    max_val = 2 ** (bits - 1) - 1

    # Clip to [-1, 1)
    coeffs_clipped = np.clip(coeffs, -1.0, 1.0 - 1.0 / max_val)

    quantized = np.round(coeffs_clipped * max_val).astype(np.int32)

    # Two's complement for negative values
    hex_strs = []
    for c in quantized:
        if c < 0:
            c_comp = c + (1 << bits)
        else:
            c_comp = c
        hex_strs.append(f"{c_comp:04X}")

    return quantized, hex_strs


def write_coe_file(filepath, hex_strs, radix=16):
    """Write .coe file for Xilinx FIR Compiler IP."""
    with open(filepath, 'w') as f:
        f.write("; FIR Coefficient file generated by fir_coeff_gen.py\n")
        f.write(f"; Taps: {len(hex_strs)}\n")
        f.write(f"; Date: 2026-05-12\n")
        f.write(f"Radix = {radix};\n")
        f.write("Coefficient_Width = 16;\n")
        f.write("CoefData = \n")
        for i, h in enumerate(hex_strs):
            comma = ',' if i < len(hex_strs) - 1 else ';'
            f.write(f"    {h}{comma}\n")
    print(f"  Wrote: {filepath}")


def write_verilog_include(filepath, hex_strs, param_name="COEFFS"):
    """Write Verilog header file with coefficient parameter array."""
    width = 16
    depth = len(hex_strs)

    with open(filepath, 'w') as f:
        f.write(f"// {os.path.basename(filepath)}\n")
        f.write(f"// FIR Coefficient memory initialization\n")
        f.write(f"// Taps: {depth}, Width: {width}-bit, Format: Q1.{width-2}\n")
        f.write(f"// Generated by fir_coeff_gen.py\n\n")
        f.write(f"localparam {param_name}_DEPTH = {depth};\n")
        f.write(f"localparam {param_name}_WIDTH = {width};\n\n")

        # Organized as 8 per line for readability
        f.write(f"wire [{width-1}:0] {param_name} [0:{depth-1}] = '{{\n")
        for i in range(0, depth, 8):
            chunk = hex_strs[i:i+8]
            line = ", ".join(f"16'h{h}" for h in chunk)
            comma = "," if i + 8 < depth else ""
            f.write(f"    {line}{comma}\n")
        f.write("};\n")

    print(f"  Wrote: {filepath}")


def plot_response(coeffs, fs, title="FIR Filter Response"):
    """Plot frequency response using matplotlib."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed. Install with: pip install matplotlib")
        return

    w, h = np_plot = __import__('scipy.signal', fromlist=['freqz']).freqz(coeffs, worN=8192)
    f = w / (2 * np.pi) * fs
    mag_db = 20 * np.log10(np.abs(h) + 1e-12)
    phase_deg = np.unwrap(np.angle(h)) * 180 / np.pi

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6))

    ax1.plot(f / 1e6, mag_db, 'b-', linewidth=1.5)
    ax1.set_ylabel('Magnitude (dB)')
    ax1.set_title(title)
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim([0, fs / 2e6])
    ax1.set_ylim([-80, 5])

    ax2.plot(f / 1e6, phase_deg, 'r-', linewidth=1.5)
    ax2.set_xlabel('Frequency (MHz)')
    ax2.set_ylabel('Phase (degrees)')
    ax2.grid(True, alpha=0.3)
    ax2.set_xlim([0, fs / 2e6])

    plt.tight_layout()
    plt.show()


def print_summary(name, coeffs, quantized, fs):
    """Print coefficient summary."""
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    print(f"  Taps:         {len(coeffs)}")
    print(f"  Sample rate:  {fs/1e6:.2f} MHz")
    print(f"  Passband:     DC ~ {fs/4/1e6:.2f} MHz (Fs/4)")
    print(f"  Window:       Hamming")

    q = np.array(quantized, dtype=np.float64)
    print(f"\n  Coeff range:  [{np.min(q):.0f}, {np.max(q):.0f}]")
    print(f"  DC gain:      {np.sum(q):.1f} (ideal: {2**15:.0f})")
    print(f"  First 5:      {[f'0x{h:04X}' for h in quantized[:5]]}")
    print(f"  Last 5:       {[f'0x{h:04X}' for h in quantized[-5:]]}")


# ==============================================================================
# Main
# ==============================================================================

def main():
    parser = argparse.ArgumentParser(description="FIR Coefficient Generator")
    parser.add_argument('--plot', action='store_true', help='Show frequency response plots')
    parser.add_argument('--fs', type=float, default=FS_DMB_BB,
                       help=f'Sampling frequency (default: {FS_DMB_BB/1e6} MHz)')
    parser.add_argument('--fc', type=float, default=BW_DMB/2,
                       help=f'Passband cutoff (default: {BW_DMB/2/1e6} MHz)')
    parser.add_argument('--taps', type=int, default=47, help='Number of taps')
    parser.add_argument('--output', type=str, default=None,
                       help='Output .coe file path')
    parser.add_argument('--window', type=str, default='hamming',
                       help='Window function (hamming/hanning/blackman/kaiser)')
    args = parser.parse_args()

    coeff_dir = os.path.abspath(COEFF_DIR)
    os.makedirs(coeff_dir, exist_ok=True)

    # ==========================================================================
    # FIR1: DMB Channel Select Filter (47 taps, decimate-by-2)
    # ==========================================================================
    print("\n--- FIR1: DMB Channel Select (47 taps, decimate-by-2) ---")

    fir1_coeffs = design_fir(
        num_taps=47,
        fs=FS_DMB_BB,
        passband_freq=BW_DMB / 2,
        window=args.window
    )
    fir1_q, fir1_hex = quantize_coeffs(fir1_coeffs, bits=16)
    print_summary("FIR1", fir1_coeffs, fir1_q, FS_DMB_BB)

    # Symmetry check
    fir1_q_arr = np.array(fir1_q)
    sym_err = np.max(np.abs(fir1_q_arr[:len(fir1_q_arr)//2]
                   - fir1_q_arr[::-1][:len(fir1_q_arr)//2]))
    print(f"  Symmetry err: {sym_err}")

    fir1_coe_path = os.path.join(coeff_dir, 'fir1_coeff.coe')
    fir1_vh_path = os.path.join(coeff_dir, 'fir1_coeff.vh')
    write_coe_file(fir1_coe_path, fir1_hex)
    write_verilog_include(fir1_vh_path, fir1_hex, param_name="FIR1_COEFF")

    if args.plot:
        plot_response(fir1_coeffs, FS_DMB_BB, "FIR1: DMB Channel Select (47 taps)")

    # ==========================================================================
    # FIR2: DMB Matched Filter (104 taps, for OFDM)
    # ==========================================================================
    print("\n--- FIR2: DMB Matched Filter (104 taps) ---")

    # Root-raised cosine for OFDM pulse shaping
    fir2_taps = 104
    span = 8  # symbols
    sps_fir2 = fir2_taps / (2 * span + 1)

    # Use raised cosine window for OFDM matched filter
    fir2_coeffs = design_fir(
        num_taps=fir2_taps,
        fs=FS_DMB_BB / 2,  # After decimate-by-2
        passband_freq=BW_DMB / 4,
        window='blackman'
    )
    fir2_q, fir2_hex = quantize_coeffs(fir2_coeffs, bits=16)
    print_summary("FIR2", fir2_coeffs, fir2_q, FS_DMB_BB / 2)

    fir2_coe_path = os.path.join(coeff_dir, 'fir2_coeff.coe')
    fir2_vh_path = os.path.join(coeff_dir, 'fir2_coeff.vh')
    write_coe_file(fir2_coe_path, fir2_hex)
    write_verilog_include(fir2_vh_path, fir2_hex, param_name="FIR2_COEFF")

    if args.plot:
        plot_response(fir2_coeffs, FS_DMB_BB / 2, "FIR2: DMB Matched Filter (104 taps)")

    # ==========================================================================
    # CIC Frequency Response Analysis
    # ==========================================================================
    print("\n--- CIC Frequency Response ---")
    print(f"\n  FM CIC:  R={693}, N={6}")
    print(f"    Output rate: {FS_DMB/693:.0f} Hz")
    print(f"    Gain: {(693)**6:.2e}")
    print(f"    Accum width: {int(np.ceil(6*np.log2(693*2**15)) + 15)} bits (design: 56)")

    print(f"\n  DMB CIC1: R={5}, N={5}")
    print(f"    Output rate: {FS_DMB/5:.0f} Hz")
    print(f"    Gain: {(5)**5:.2e}")
    print(f"    Accum width: {int(np.ceil(5*np.log2(5*2**15)) + 15)} bits (design: 28)")

    print(f"\n  DMB CIC2: R={5}, N={4}")
    print(f"    Output rate: {FS_DMB/5/5:.0f} Hz")
    print(f"    Gain: {(5)**4:.2e}")
    print(f"    Accum width: {int(np.ceil(4*np.log2(5*2**15)) + 15)} bits (design: 24)")

    # ==========================================================================
    # CIC droop compensation (ISOP)
    # ==========================================================================
    print("\n--- ISOP Coefficient ---")
    # Default: c = 0xF000 in 4.12 format = -1.0
    isop_c = np.arange(-2.0, 0.0, 0.125)
    print(f"  ISOP: y[n] = x[n] - c*x[n-1] + x[n-2]")
    print(f"  Recommended c range: {-1.5:.1f} to {-0.5:.1f} (4.12 format)")
    print(f"  Default: c = 0xF000 ({-1.0:.1f})")

    # Compute ISOP response for c = -1.0
    try:
        from scipy import signal
        isop_b = [1.0, 1.0, 1.0]  # c = -1.0
        isop_w, isop_h = signal.freqz(isop_b, [1], worN=8192)
        isop_mag = 20 * np.log10(np.abs(isop_h) + 1e-12)
        print(f"  ISOP max compensation: {np.max(isop_mag):.1f} dB @ DC")
        print(f"  ISOP @ 0.5*Fs: {isop_mag[len(isop_mag)//2]:.1f} dB")
    except ImportError:
        pass

    print(f"\n{'='*60}")
    print(f"  Output files in: {coeff_dir}")
    print(f"  Generated files:")
    for f in ['fir1_coeff.coe', 'fir1_coeff.vh', 'fir2_coeff.coe', 'fir2_coeff.vh']:
        path = os.path.join(coeff_dir, f)
        if os.path.exists(path):
            print(f"    ✓ {path}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
